apiVersion: apps/v1
kind: Deployment
metadata:
  name: homework-deployment
  labels:
    app: game
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector: 
    matchLabels:
      app: my-kubedoom-app
  template:
    metadata:
      labels:
        app: my-kubedoom-app
    spec:
      hostNetwork: true
      serviceAccountName: kubedoom
      containers:
      - image: storaxdev/kubedoom:0.5.0
        name: my-kubedoom-app
        ports:
        - containerPort: 5900
